spring:
  batch:
    jdbc:
      initialize-schema: always
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ENC(N9ZF9W2LrxymS/eFSbWzvN0wVCYmT/DlNvyr4szG683Ro821j9AXtntQG6EhzOw+GPdBVeBzFd8Dck9DrNit+VlWAJtqi8GmyCUXI7JbjFwwB45Nibrz/oZ8qX1TwLt1C6CdGKM1zo5jEl2vuuZFtIMKm+OyoYJ9qHC/5DAItpLfUJyYl8svv1NKWf/vDMZy)
    user: ENC(EUc5lpk9Sn77473PV6hm7Q==)
    password: ENC(7pCO5qSn9x5VNppvYxsJUrZLTfWiNggsIrFpPpTSjyI=)
    locations: classpath:/db/migration
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ENC(N9ZF9W2LrxymS/eFSbWzvN0wVCYmT/DlNvyr4szG683Ro821j9AXtntQG6EhzOw+GPdBVeBzFd8Dck9DrNit+VlWAJtqi8GmyCUXI7JbjFwwB45Nibrz/oZ8qX1TwLt1C6CdGKM1zo5jEl2vuuZFtIMKm+OyoYJ9qHC/5DAItpLfUJyYl8svv1NKWf/vDMZy)
    username: ENC(EUc5lpk9Sn77473PV6hm7Q==)
    password: ENC(7pCO5qSn9x5VNppvYxsJUrZLTfWiNggsIrFpPpTSjyI=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  #        format_sql: true
  #        show_sql: true
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    bean: jasyptStringEncryptor

auth0:
  domain: dev-o4pgsljdj1aisk3y.us.auth0.com
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  redirect-uri: dev-o4pgsljdj1aisk3y.us.auth0.com/auth/login
  issuer: ${AUTH0_ISSUER}
  audience: ${AUTH0_AUDIENCE}

auth:
  jwt:
    secret: ${JWT_SECRET}
    access:
      expiration-ms: 900000         # 액세스 토큰: 15분 예시
    refresh:
      expiration-ms: 1209600000     # 리프레시 토큰: 14일(14*24*60*60*1000)

